services:
  logstash:
    image: logstash:8.10.2
    depends_on:
      - elasticsearch
    environment:
      # Так как сейчас вы хотите запустить logstash без Elasticsearch,
      # необходимо отключить встроенный мониторинг, отправляющий данные в ES.
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      # Монтируем файл с конфигурацией logstash
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    # Запускаем с указанием конфигурационного файла
    command: logstash -f /config/logstash.conf

  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      # Указываем ES запуститься в одном экземпляре
      - discovery.type=single-node
      # Пока не будем беспокоиться о безопасности
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 

volumes:
  esdata: